# _config.yml

title: "Naftah Language Documentation - مستندات لغة نفطه"
description: "Documentation and guides for Naftah programming language"
baseurl: ""
url:  "https://naftah.daiitech.org"

github:
  username: "Chakib-DAII"
  repo: "Naftah"

permalink: pretty      # nice clean URLs without .html
theme: minima          # built-in simple theme (easy to customize)
markdown: kramdown     # recommended Markdown parser
kramdown:
  input: GFM           # GitHub Flavored Markdown

plugins:
  - jekyll-seo-tag    # for SEO improvements
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

copy_data_files:
  - file: jvm-class-initializers.json
  - file: jvm-functions.json
    compress: true

