name: CI

on:
  push:
    branches: [ '**' ]      # all branches
  pull_request:
    branches: [ '**' ]      # all branches for PRs

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java (Temurin 17)
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Run Checkstyle
        run: ./gradlew checkstyleMain checkstyleTest checkstyleBenchmark spotlessCheck || true

      - name: Upload Checkstyle report artifact (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: gradle-checkstyle-report
          path: build/reports/checkstyle

  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java (Temurin 17)
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew clean build -x test

      - name: Upload problems report artifact (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: gradle-problems-report
          path: build/reports/problems

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java (Temurin 17)
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Run tests with coverage
        #      - name: Run tests with coverage and enforce threshold
        run: ./gradlew test jacocoTestReport
      #        run: ./gradlew test jacocoTestReport jacocoTestCoverageVerification

      - name: Upload Gradle test results artifact
        uses: actions/upload-artifact@v4
        with:
          name: gradle-test-results
          path: build/reports/tests/test

      - name: Upload JaCoCo HTML coverage report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-html-report
          path: build/reports/jacoco/test/html

      - name: Upload JaCoCo XML report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-xml-report
          path: build/reports/jacoco/test/jacocoTestReport.xml

  report:
    runs-on: ubuntu-latest
    needs: [ lint, build, test ]   # depends on all these jobs
    steps:
      - name: Debug needs
        run: |
          echo "Test job result: ${{ needs.lint.result }}"
          echo "Test job result: ${{ needs.lint.outcome }}"
          echo "Test job result: ${{ needs.build.result }}"
          echo "Test job result: ${{ needs.build.outcome }}"
          echo "Test job result: ${{ needs.test.result }}"
          echo "Test job result: ${{ needs.test.outcome }}"
      - name: Download Checkstyle report artifact
        if: needs.lint.outcome == 'failure'
        uses: actions/download-artifact@v4
        with:
          name: gradle-checkstyle-report
          path: build/reports/checkstyle

      - name: Download problems report artifact
        if: needs.build.outcome == 'failure'
        uses: actions/download-artifact@v4
        with:
          name: gradle-problems-report
          path: build/reports/problems

      - name: Download Gradle test results artifact
        if: needs.test.outcome == 'success'
        uses: actions/download-artifact@v4
        with:
          name: gradle-test-results
          path: build/reports/tests/test

      - name: Download JaCoCo HTML report
        if: needs.test.outcome == 'success'
        uses: actions/download-artifact@v4
        with:
          name: jacoco-html-report
          path: build/reports/jacoco/test/html

      - name: Download JaCoCo XML report
        if: needs.test.outcome == 'success'
        uses: actions/download-artifact@v4
        with:
          name: jacoco-xml-report
          path: build/reports/jacoco/test/jacocoTestReport.xml